
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.registrated;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-02-09T22:49:28.242+01:00
 * Generated source version: 2.7.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuthenticationService",
                      portName = "AuthenticationPort",
                      targetNamespace = "http://www.example.org/registrated/",
                      wsdlLocation = "file:/home/stefan/workspaceEE2/ff6/src/registrated.wsdl",
                      endpointInterface = "org.example.registrated.Authentication")
                      
public class AuthenticationImpl implements Authentication {
	
	private String password = "password";
	private String authToken = "access_granted";
    private static final Logger LOG = Logger.getLogger(AuthenticationImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.registrated.Authentication#getAuthToken(java.lang.String  arg1 )*
     */
    public java.lang.String getAuthToken(java.lang.String arg1) { 
        LOG.info("Executing operation getAuthToken");
        System.out.println(arg1);
        if(arg1.equals(password)){
        	return authToken;
        }
        else{
        	return "access_denied";
        }
    }

}
